---
name: "Build"

on:
  push:
    paths-ignore:
      - "**.md"

env:
  IMAGE_NAME: blt950/where2fly

jobs:
  build-container:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: configure docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=pr
            type=sha,event=branch,prefix=
            type=semver,event=tag,pattern=v{{version}}
            type=semver,event=tag,pattern=v{{major}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Checkout open repo
        uses: actions/checkout@v3
        with:
          repository: blt950/where2fly

      - name: Checkout private fonts repo
        uses: actions/checkout@v3
        with:
          repository: blt950/where2fly-fonts
          token: ${{ secrets.FONTS_REPO_TOKEN }}
          path: fonts-repo

      - name: Copy fonts
        run: |
          mkdir -p resources/fonts
          cp -r fonts-repo/* resources/fonts/
          ls -la resources/fonts

      - name: build & push container image
        uses: docker/build-push-action@v6
        with:
          context: "."
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
